openapi: 3.0.1
info:
  title: POC
  description: ''
  version: '1.0'
servers:
  - url: https://dev-apim-arnedeproft.azure-api.net/tomtom
paths:
  /echo:
    get:
      summary: maps
      operationId: getsessions
      responses:
        '200':
          description: 
  /traffic:
    get:
      summary: traffic
      operationId: getspeakers
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]